/**
 * Generates `vendo/profile.generated.ts` from the `.vendo/` sources.
 *
 * Why: the Worker bundle cannot read `.vendo/` at runtime (workerd has no
 * filesystem, and rolldown compiles `readFileSync(new URL(...))` into a
 * runtime read that crashes startup). This script flattens the profile into
 * pure data literals at build time; every bundler inlines them.
 *
 * Run automatically by `predev`/`prebuild` after `vendo sync`, so the
 * generated module never drifts from the machine layer. `vendo:check`
 * regenerates and diffs it in CI.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const dotVendo = (name: string) => join(repoRoot, ".vendo", name);

const readJson = (name: string): unknown =>
  JSON.parse(readFileSync(dotVendo(name), "utf8"));

const tools = readJson("tools.json");
const overrides = readJson("overrides.json");
const policy = readJson("policy.json");
const theme = readJson("theme.json");
const catalog = readJson("catalog.json");
const brief = readFileSync(dotVendo("brief.md"), "utf8");

const header = `// @generated by scripts/gen-vendo-profile.ts — do not edit by hand.
// Regenerate with \`bun run vendo:profile\` (run automatically on dev/build).
`;

const body = `${header}
import type { ExtractedTool, OverridesFile } from "@vendoai/actions";
import type { PolicyFile } from "@vendoai/guard";
import type { VendoTheme } from "@vendoai/apps/contract";
import type { CatalogFile } from "@vendoai/vendo/server";

/** \`.vendo/tools.json\` — the machine layer \`vendo sync\` regenerates wholesale. */
export const TOOLS_FILE = ${JSON.stringify(tools, null, 2)} as {
  tools?: ExtractedTool[];
};

/** \`.vendo/overrides.json\` — the only human-edited layer (risk grades, etc.). */
export const OVERRIDES_FILE = ${JSON.stringify(overrides, null, 2)} as OverridesFile;

/** \`.vendo/policy.json\` — the authoritative guard policy document. */
export const POLICY_FILE = ${JSON.stringify(policy, null, 2)} as PolicyFile;

/** \`.vendo/theme.json\` — the Manorama brand surface. */
export const THEME_FILE = ${JSON.stringify(theme, null, 2)} as VendoTheme;

/** \`.vendo/catalog.json\` — the named tool groups the console lists. */
export const CATALOG_FILE = ${JSON.stringify(catalog, null, 2)} as CatalogFile;

/** \`.vendo/brief.md\` — the operator brief. */
export const BRIEF = ${JSON.stringify(brief)};
`;

const outPath = join(repoRoot, "vendo", "profile.generated.ts");
writeFileSync(outPath, body);
console.log(`[vendo-profile] wrote ${outPath} (${body.length} bytes)`);
